baseURL = "https://evanandrewsdev.github.io/mothers-day-site/"
languageCode = "en-us"
title = "Happy Mothers Day"
theme = "ananke"

[params]
  mainSections = ["home"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

